// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: actions.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const getAnomalyForUpdate = `-- name: GetAnomalyForUpdate :one
SELECT id, meter_id, fingerprint, type, severity, confidence, confidence_breakdown, priority, priority_breakdown, episode_start, episode_end, ongoing, evidence, reason, recommended_action, investigation_steps, explanation_source, explanation_model, status, detected_at, last_analysis_id, summary FROM anomalies WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAnomalyForUpdate(ctx context.Context, id string) (Anomaly, error) {
	row := q.db.QueryRowContext(ctx, getAnomalyForUpdate, id)
	var i Anomaly
	err := row.Scan(
		&i.ID,
		&i.MeterID,
		&i.Fingerprint,
		&i.Type,
		&i.Severity,
		&i.Confidence,
		&i.ConfidenceBreakdown,
		&i.Priority,
		&i.PriorityBreakdown,
		&i.EpisodeStart,
		&i.EpisodeEnd,
		&i.Ongoing,
		&i.Evidence,
		&i.Reason,
		&i.RecommendedAction,
		&i.InvestigationSteps,
		&i.ExplanationSource,
		&i.ExplanationModel,
		&i.Status,
		&i.DetectedAt,
		&i.LastAnalysisID,
		&i.Summary,
	)
	return i, err
}

const insertAnomalyAction = `-- name: InsertAnomalyAction :one
INSERT INTO anomaly_actions (anomaly_id, user_id, action, note, from_status, to_status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, anomaly_id, user_id, action, note, from_status, to_status, created_at
`

type InsertAnomalyActionParams struct {
	AnomalyID  string
	UserID     string
	Action     string
	Note       sql.NullString
	FromStatus string
	ToStatus   string
}

func (q *Queries) InsertAnomalyAction(ctx context.Context, arg InsertAnomalyActionParams) (AnomalyAction, error) {
	row := q.db.QueryRowContext(ctx, insertAnomalyAction,
		arg.AnomalyID,
		arg.UserID,
		arg.Action,
		arg.Note,
		arg.FromStatus,
		arg.ToStatus,
	)
	var i AnomalyAction
	err := row.Scan(
		&i.ID,
		&i.AnomalyID,
		&i.UserID,
		&i.Action,
		&i.Note,
		&i.FromStatus,
		&i.ToStatus,
		&i.CreatedAt,
	)
	return i, err
}

const listAnomalyActions = `-- name: ListAnomalyActions :many
SELECT a.id, a.anomaly_id, a.user_id, u.name AS user_name, a.action, a.note,
       a.from_status, a.to_status, a.created_at
FROM anomaly_actions a
JOIN users u ON u.id = a.user_id
WHERE a.anomaly_id = $1
ORDER BY a.created_at, a.id
`

type ListAnomalyActionsRow struct {
	ID         string
	AnomalyID  string
	UserID     string
	UserName   string
	Action     string
	Note       sql.NullString
	FromStatus string
	ToStatus   string
	CreatedAt  time.Time
}

func (q *Queries) ListAnomalyActions(ctx context.Context, anomalyID string) ([]ListAnomalyActionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAnomalyActions, anomalyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnomalyActionsRow
	for rows.Next() {
		var i ListAnomalyActionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AnomalyID,
			&i.UserID,
			&i.UserName,
			&i.Action,
			&i.Note,
			&i.FromStatus,
			&i.ToStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAnomalyStatus = `-- name: SetAnomalyStatus :exec
UPDATE anomalies SET status = $2 WHERE id = $1
`

type SetAnomalyStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) SetAnomalyStatus(ctx context.Context, arg SetAnomalyStatusParams) error {
	_, err := q.db.ExecContext(ctx, setAnomalyStatus, arg.ID, arg.Status)
	return err
}
