// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: anomalies.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const getAnomaly = `-- name: GetAnomaly :one
SELECT id, meter_id, fingerprint, type, severity, confidence, confidence_breakdown, priority, priority_breakdown, episode_start, episode_end, ongoing, evidence, reason, recommended_action, investigation_steps, explanation_source, explanation_model, status, detected_at, last_analysis_id, summary FROM anomalies WHERE id = $1
`

func (q *Queries) GetAnomaly(ctx context.Context, id string) (Anomaly, error) {
	row := q.db.QueryRowContext(ctx, getAnomaly, id)
	var i Anomaly
	err := row.Scan(
		&i.ID,
		&i.MeterID,
		&i.Fingerprint,
		&i.Type,
		&i.Severity,
		&i.Confidence,
		&i.ConfidenceBreakdown,
		&i.Priority,
		&i.PriorityBreakdown,
		&i.EpisodeStart,
		&i.EpisodeEnd,
		&i.Ongoing,
		&i.Evidence,
		&i.Reason,
		&i.RecommendedAction,
		&i.InvestigationSteps,
		&i.ExplanationSource,
		&i.ExplanationModel,
		&i.Status,
		&i.DetectedAt,
		&i.LastAnalysisID,
		&i.Summary,
	)
	return i, err
}

const listAnomalies = `-- name: ListAnomalies :many
SELECT id, meter_id, fingerprint, type, severity, confidence, confidence_breakdown, priority, priority_breakdown, episode_start, episode_end, ongoing, evidence, reason, recommended_action, investigation_steps, explanation_source, explanation_model, status, detected_at, last_analysis_id, summary FROM anomalies
WHERE ($1::text     IS NULL OR type     = $1)
  AND ($2::text IS NULL OR severity = $2)
  AND ($3::text   IS NULL OR status   = $3)
  AND ($4::text IS NULL OR meter_id = $4)
ORDER BY priority DESC, confidence DESC, meter_id, episode_start
`

type ListAnomaliesParams struct {
	Type     sql.NullString
	Severity sql.NullString
	Status   sql.NullString
	MeterID  sql.NullString
}

// Every filter is optional: a NULL one matches everything.
func (q *Queries) ListAnomalies(ctx context.Context, arg ListAnomaliesParams) ([]Anomaly, error) {
	rows, err := q.db.QueryContext(ctx, listAnomalies,
		arg.Type,
		arg.Severity,
		arg.Status,
		arg.MeterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Anomaly
	for rows.Next() {
		var i Anomaly
		if err := rows.Scan(
			&i.ID,
			&i.MeterID,
			&i.Fingerprint,
			&i.Type,
			&i.Severity,
			&i.Confidence,
			&i.ConfidenceBreakdown,
			&i.Priority,
			&i.PriorityBreakdown,
			&i.EpisodeStart,
			&i.EpisodeEnd,
			&i.Ongoing,
			&i.Evidence,
			&i.Reason,
			&i.RecommendedAction,
			&i.InvestigationSteps,
			&i.ExplanationSource,
			&i.ExplanationModel,
			&i.Status,
			&i.DetectedAt,
			&i.LastAnalysisID,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAnomaly = `-- name: UpsertAnomaly :exec
INSERT INTO anomalies (
    meter_id, fingerprint, type, severity, confidence, confidence_breakdown,
    priority, priority_breakdown, episode_start, episode_end, ongoing, evidence,
    summary, reason, recommended_action, investigation_steps,
    explanation_source, explanation_model, last_analysis_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
)
ON CONFLICT (fingerprint) DO UPDATE SET
    severity             = EXCLUDED.severity,
    confidence           = EXCLUDED.confidence,
    confidence_breakdown = EXCLUDED.confidence_breakdown,
    priority             = EXCLUDED.priority,
    priority_breakdown   = EXCLUDED.priority_breakdown,
    episode_end          = EXCLUDED.episode_end,
    ongoing              = EXCLUDED.ongoing,
    evidence             = EXCLUDED.evidence,
    summary              = EXCLUDED.summary,
    reason               = EXCLUDED.reason,
    recommended_action   = EXCLUDED.recommended_action,
    investigation_steps  = EXCLUDED.investigation_steps,
    explanation_source   = EXCLUDED.explanation_source,
    explanation_model    = EXCLUDED.explanation_model,
    last_analysis_id     = EXCLUDED.last_analysis_id
`

type UpsertAnomalyParams struct {
	MeterID             string
	Fingerprint         string
	Type                string
	Severity            string
	Confidence          float64
	ConfidenceBreakdown json.RawMessage
	Priority            int32
	PriorityBreakdown   json.RawMessage
	EpisodeStart        time.Time
	EpisodeEnd          time.Time
	Ongoing             bool
	Evidence            json.RawMessage
	Summary             string
	Reason              string
	RecommendedAction   string
	InvestigationSteps  json.RawMessage
	ExplanationSource   string
	ExplanationModel    sql.NullString
	LastAnalysisID      string
}

// A re-run finds the same anomaly by fingerprint. It refreshes what the engine
// measured and wrote, and leaves id, status and detected_at as they were.
func (q *Queries) UpsertAnomaly(ctx context.Context, arg UpsertAnomalyParams) error {
	_, err := q.db.ExecContext(ctx, upsertAnomaly,
		arg.MeterID,
		arg.Fingerprint,
		arg.Type,
		arg.Severity,
		arg.Confidence,
		arg.ConfidenceBreakdown,
		arg.Priority,
		arg.PriorityBreakdown,
		arg.EpisodeStart,
		arg.EpisodeEnd,
		arg.Ongoing,
		arg.Evidence,
		arg.Summary,
		arg.Reason,
		arg.RecommendedAction,
		arg.InvestigationSteps,
		arg.ExplanationSource,
		arg.ExplanationModel,
		arg.LastAnalysisID,
	)
	return err
}
