// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlcgen

import (
	"context"
)

const listEvents = `-- name: ListEvents :many
SELECT id, meter_id, ts, type, description
FROM events
ORDER BY ts, meter_id
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.MeterID,
			&i.Ts,
			&i.Type,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeterEvents = `-- name: ListMeterEvents :many
SELECT id, meter_id, ts, type, description
FROM events
WHERE meter_id = $1
ORDER BY ts
`

func (q *Queries) ListMeterEvents(ctx context.Context, meterID string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listMeterEvents, meterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.MeterID,
			&i.Ts,
			&i.Type,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
