// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: explanations.sql

package sqlcgen

import (
	"context"
	"encoding/json"
)

const getCachedExplanation = `-- name: GetCachedExplanation :one
SELECT payload, model FROM explanation_cache WHERE evidence_hash = $1
`

type GetCachedExplanationRow struct {
	Payload json.RawMessage
	Model   string
}

func (q *Queries) GetCachedExplanation(ctx context.Context, evidenceHash string) (GetCachedExplanationRow, error) {
	row := q.db.QueryRowContext(ctx, getCachedExplanation, evidenceHash)
	var i GetCachedExplanationRow
	err := row.Scan(&i.Payload, &i.Model)
	return i, err
}

const putCachedExplanation = `-- name: PutCachedExplanation :exec
INSERT INTO explanation_cache (evidence_hash, provider, model, payload)
VALUES ($1, $2, $3, $4)
ON CONFLICT (evidence_hash) DO NOTHING
`

type PutCachedExplanationParams struct {
	EvidenceHash string
	Provider     string
	Model        string
	Payload      json.RawMessage
}

func (q *Queries) PutCachedExplanation(ctx context.Context, arg PutCachedExplanationParams) error {
	_, err := q.db.ExecContext(ctx, putCachedExplanation,
		arg.EvidenceHash,
		arg.Provider,
		arg.Model,
		arg.Payload,
	)
	return err
}
