// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meters.sql

package sqlcgen

import (
	"context"
)

const getMeter = `-- name: GetMeter :one
SELECT id, meter_id, name, location, created_at
FROM meters
WHERE meter_id = $1
`

func (q *Queries) GetMeter(ctx context.Context, meterID string) (Meter, error) {
	row := q.db.QueryRowContext(ctx, getMeter, meterID)
	var i Meter
	err := row.Scan(
		&i.ID,
		&i.MeterID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const listMeters = `-- name: ListMeters :many
SELECT id, meter_id, name, location, created_at
FROM meters
ORDER BY meter_id
`

func (q *Queries) ListMeters(ctx context.Context) ([]Meter, error) {
	rows, err := q.db.QueryContext(ctx, listMeters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meter
	for rows.Next() {
		var i Meter
		if err := rows.Scan(
			&i.ID,
			&i.MeterID,
			&i.Name,
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
