// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AnalysisRun struct {
	ID           string
	Status       string
	CurrentStage sql.NullString
	Stages       json.RawMessage
	Summary      *json.RawMessage
	Params       json.RawMessage
	StartedAt    time.Time
	FinishedAt   sql.NullTime
}

type Anomaly struct {
	ID                  string
	MeterID             string
	Fingerprint         string
	Type                string
	Severity            string
	Confidence          float64
	ConfidenceBreakdown json.RawMessage
	Priority            int32
	PriorityBreakdown   json.RawMessage
	EpisodeStart        time.Time
	EpisodeEnd          time.Time
	Ongoing             bool
	Evidence            json.RawMessage
	Reason              string
	RecommendedAction   string
	InvestigationSteps  json.RawMessage
	ExplanationSource   string
	ExplanationModel    sql.NullString
	Status              string
	DetectedAt          time.Time
	LastAnalysisID      string
}

type AnomalyAction struct {
	ID         string
	AnomalyID  string
	UserID     string
	Action     string
	Note       sql.NullString
	FromStatus string
	ToStatus   string
	CreatedAt  time.Time
}

type Event struct {
	ID          string
	MeterID     string
	Ts          time.Time
	Type        string
	Description string
}

type ExplanationCache struct {
	EvidenceHash string
	Provider     string
	Model        string
	Payload      json.RawMessage
	CreatedAt    time.Time
}

type Meter struct {
	ID        string
	MeterID   string
	Name      string
	Location  string
	CreatedAt time.Time
}

type Reading struct {
	ID             int64
	MeterID        string
	Ts             time.Time
	ConsumptionKwh float64
	VoltageV       float64
	CurrentA       float64
	PowerFactor    float64
	Status         string
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	Name         string
	CreatedAt    time.Time
}
