// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: readings.sql

package sqlcgen

import (
	"context"
	"time"
)

const listMeterReadings = `-- name: ListMeterReadings :many
SELECT id, meter_id, ts, consumption_kwh, voltage_v, current_a, power_factor, status
FROM readings
WHERE meter_id = $1
  AND ts >= $2
  AND ts < $3
ORDER BY ts
`

type ListMeterReadingsParams struct {
	MeterID string
	FromTs  time.Time
	ToTs    time.Time
}

// The range is [from_ts, to_ts): the upper bound is exclusive.
func (q *Queries) ListMeterReadings(ctx context.Context, arg ListMeterReadingsParams) ([]Reading, error) {
	rows, err := q.db.QueryContext(ctx, listMeterReadings, arg.MeterID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reading
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.ID,
			&i.MeterID,
			&i.Ts,
			&i.ConsumptionKwh,
			&i.VoltageV,
			&i.CurrentA,
			&i.PowerFactor,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadings = `-- name: ListReadings :many
SELECT id, meter_id, ts, consumption_kwh, voltage_v, current_a, power_factor, status
FROM readings
ORDER BY meter_id, ts
`

func (q *Queries) ListReadings(ctx context.Context) ([]Reading, error) {
	rows, err := q.db.QueryContext(ctx, listReadings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reading
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.ID,
			&i.MeterID,
			&i.Ts,
			&i.ConsumptionKwh,
			&i.VoltageV,
			&i.CurrentA,
			&i.PowerFactor,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
