// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createRun = `-- name: CreateRun :one
INSERT INTO analysis_runs (params, stages)
VALUES ($1, $2)
RETURNING id, status, current_stage, stages, summary, params, started_at, finished_at
`

type CreateRunParams struct {
	Params json.RawMessage
	Stages json.RawMessage
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (AnalysisRun, error) {
	row := q.db.QueryRowContext(ctx, createRun, arg.Params, arg.Stages)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CurrentStage,
		&i.Stages,
		&i.Summary,
		&i.Params,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishRun = `-- name: FinishRun :exec
UPDATE analysis_runs
SET status = $2, current_stage = NULL, stages = $3, summary = $4, finished_at = now()
WHERE id = $1
`

type FinishRunParams struct {
	ID      string
	Status  string
	Stages  json.RawMessage
	Summary *json.RawMessage
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) error {
	_, err := q.db.ExecContext(ctx, finishRun,
		arg.ID,
		arg.Status,
		arg.Stages,
		arg.Summary,
	)
	return err
}

const getActiveRun = `-- name: GetActiveRun :one
SELECT id, status, current_stage, stages, summary, params, started_at, finished_at FROM analysis_runs
WHERE status IN ('PENDING', 'RUNNING')
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetActiveRun(ctx context.Context) (AnalysisRun, error) {
	row := q.db.QueryRowContext(ctx, getActiveRun)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CurrentStage,
		&i.Stages,
		&i.Summary,
		&i.Params,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getLatestCompletedRun = `-- name: GetLatestCompletedRun :one
SELECT id, status, current_stage, stages, summary, params, started_at, finished_at FROM analysis_runs
WHERE status = 'COMPLETED'
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLatestCompletedRun(ctx context.Context) (AnalysisRun, error) {
	row := q.db.QueryRowContext(ctx, getLatestCompletedRun)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CurrentStage,
		&i.Stages,
		&i.Summary,
		&i.Params,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getLatestRun = `-- name: GetLatestRun :one
SELECT id, status, current_stage, stages, summary, params, started_at, finished_at FROM analysis_runs ORDER BY started_at DESC LIMIT 1
`

func (q *Queries) GetLatestRun(ctx context.Context) (AnalysisRun, error) {
	row := q.db.QueryRowContext(ctx, getLatestRun)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CurrentStage,
		&i.Stages,
		&i.Summary,
		&i.Params,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, status, current_stage, stages, summary, params, started_at, finished_at FROM analysis_runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id string) (AnalysisRun, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CurrentStage,
		&i.Stages,
		&i.Summary,
		&i.Params,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateRunProgress = `-- name: UpdateRunProgress :exec
UPDATE analysis_runs
SET status = $2, current_stage = $3, stages = $4
WHERE id = $1
`

type UpdateRunProgressParams struct {
	ID           string
	Status       string
	CurrentStage sql.NullString
	Stages       json.RawMessage
}

func (q *Queries) UpdateRunProgress(ctx context.Context, arg UpdateRunProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateRunProgress,
		arg.ID,
		arg.Status,
		arg.CurrentStage,
		arg.Stages,
	)
	return err
}
